### ISSUE TITLE
OAuth Use Project Settings

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/lookit-api#54]
Nice `fake` creds, wouldn't it be better if these were project settings?

https://github.com/CenterForOpenScience/lookit-api/blob/7826969018d276e5abc81c11e98896d0c45b6eeb/accounts/signals.py#L34-L35

**Comment by pattisdr** [comment]
addressed in https://github.com/CenterForOpenScience/lookit-api/pull/58
