### ISSUE TITLE
Static Pages Should Use Relative Root

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/lookit-api#56]
There are ~23 entries in this file with:
`https://storage.googleapis.com/io-osf-lookit-staging2/static/images/nsf.gif`

I believe these would work if updated to `/static/images/nsf.gif`.

e.g. 
https://github.com/CenterForOpenScience/lookit-api/blob/7826969018d276e5abc81c11e98896d0c45b6eeb/accounts/signals.py#L143

**Comment by pattisdr** [comment]
addressed in https://github.com/CenterForOpenScience/lookit-api/pull/58
